---
version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: stormrage_gatling
    volumes:
      - '~/Desktop/redis/data/:/data/'
    ports:
      - 6379:6379
    expose:
      - 6379