FROM grafana/grafana:latest

ADD ./provisioning /etc/grafana/provisioning
ADD ./grafana.ini /etc/grafana/grafana.ini
ADD ./dashboards /var/lib/grafana/dashboards
ADD ./plugins /var/lib/grafana/plugins
