{
 "title": "Gatling Report Trend (GIT)",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "influxdb" },
   { "name": "archive", "label": "Retention policy (archive)", "query": "SHOW RETENTION POLICIES" },
   { "name": "new", "label": "Retention policy (new)", "query": "SHOW RETENTION POLICIES" },
   {
    "name": "simulation",
    "label": "Simulation",
    "query": "SELECT DISTINCT(\"simulation\") FROM \n  (SELECT last(\"mean\") FROM \"$new\".\"gatling\" GROUP BY \"simulation\"),\n  (SELECT last(\"mean\") FROM \"$archive\".\"gatling\" GROUP BY \"simulation\")\nWHERE $timeFilter"
   },
   {
    "name": "mean_max",
    "query": "SELECT max(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_mean",
    "query": "SELECT mean(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "mean_median",
    "query": "SELECT median(\"Mean\") FROM (\nSELECT mean(\"mean\") as \"Mean\"\n   FROM  \"autogen\".\"gatling\"\n   WHERE \"request\" = 'allRequests'\n         AND \"status\" = 'ok'\n         AND \"simulation\" =~ /^${simulation:regex}$/\n         AND $timeFilter\n   GROUP BY \"run\"\n)"
   },
   {
    "name": "duration_median",
    "query": "SELECT median(\"Duration\") FROM (\nSELECT SUM(\"e\") as \"Duration\" FROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Mean Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Mean Time + Mean / max(Mean)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_max}" ], "type": "math" },
       { "params": [ "Mean / max(Mean)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Mean Time + Mean analitics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_max}" ], "type": "math" },
       { "params": [ "Mean / max(Mean)" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_mean}" ], "type": "math" },
       { "params": [ "Mean / mean(Mean)" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_median}" ], "type": "math" },
       { "params": [ "Mean / median(Mean)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Test: %OK and %Fail ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT SUM(\"e\") as \"Duration\" FROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "1s" ], "type": "elapsed" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration with Finish Time (precise)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(1s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "elapsed" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration with Finish Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(10s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "elapsed" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration with Finish Time  join  Total",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(10s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "elapsed" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration with Finish Time",
   "type": "table",
   "gridPos": { "h": 23, "w": 5, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT last(\"d\") AS \"Duration\"\nFROM (\n    SELECT cumulative_sum(elapsed(last(\"count\"), 1s)) AS \"d\"\n    FROM \"$archive\".\"gatling\"\n    WHERE \"simulation\" = '$simulation' AND $timeFilter\n    GROUP BY time(1s),  \"run\"\n) \nWHERE $timeFilter\nGROUP BY \"run\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "elapsed" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "simulation", "operator": "=~", "value": "/^$simulation$/" },
      { "condition": "AND", "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Test: %OK and %Fail ",
   "type": "table",
   "gridPos": { "h": 23, "w": 14, "x": 5, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "OK" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Mean" ], "type": "alias" }
      ],
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / ${mean_median}" ], "type": "math" },
       { "params": [ "Mean / median(Mean)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "KO" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "run" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "simulation", "operator": "=~", "value": "/^$simulation$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Duration\", \"Duration\" / ${duration_median} as \"Duration / median(Duration)\",  \"run\"\nFROM (\nSELECT SUM(\"e\") as \"Duration\" \nFROM\n(SELECT elapsed(\"count\", 1s) as \"e\" FROM \"$archive\".\"gatling\" WHERE (\"request\" = 'allRequests' AND \"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"run\")\nGROUP BY  \"run\"\n)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "events",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}